// Users manager
export const LIST_ALL_USERS = "LIST_ALL_USERS";
export const SAVE_USER = "SAVE_USER";
export const ADD_USER = "ADD_USER";
export const TOGGLE_USER_FORM = "TOGGLE_USER_FORM";
export const DELETE_USER = "DELETE_USER";
export const GET_USER_EDITING = "GET_USER_EDITING";
export const UPDATE_USER_STATUS = "UPDATE_USER_STATUS";
export const UPDATE_USER = "UPDATE_USER";
export const FILTER_USER = "FILTER_USER";

// Movies manager

export const LIST_ALL_MOVIES = "LIST_ALL_MOVIES";
export const ADD_MOVIE = "ADD_MOVIE";
export const SAVE_MOVIE = "SAVE_MOVIE";
export const TOGGLE_MOVIE_MODAL = "TOGGLE_MOVIE_MODAL";
export const TOGGLE_MOVIE_FORM = "TOGGLE_MOVIE_FORM";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const EDIT_MOVIE = "EDIT_MOVIE";
export const UPDATE_MOVIE = "UPDATE_MOVIE";
export const FILTER_MOVIE = "FILTER_MOVIE";
export const GET_MOVIE_INFO = "GET_MOVIE_INFO";
// Genres
export const LIST_ALL_GENRES = "LIST_ALL_GENRES";

// Actors

export const LIST_ALL_ACTORS = "LIST_ALL_ACTORS";
export const SAVE_ACTOR = "SAVE_ACTOR";
export const TOGGLE_ACTOR_MODAL = "TOGGLE_ACTOR_MODAL";
export const TOGGLE_ACTOR_FORM = "TOGGLE_ACTOR_FORM";
export const DELETE_ACTOR = "DELETE_ACTOR";
export const GET_ACTOR_INFO = "GET_ACTOR_INFO";
export const UPDATE_ACTOR = "UPDATE_ACTOR";
export const FILTER_ACTOR = "FILTER_ACTOR";

export const FETCH_DATA_CINEMA = "FETCH_DATA_CINEMA";
export const FETCH_DATA_SHOWTIME = "FETCH_DATA_SHOWTIME";

// showtime manager
export const GET_SHOWTIME = "GET_SHOWTIME";
export const GET_ALL_CINEMAS = "GET_ALL_CINEMAS";
export const GET_CINEMA_ROOMS = "GET_CINEMA_ROOMS";
export const GET_ALL_MOVIES_SHOWTIMES = "GET_ALL_MOVIES_SHOWTIMES";
export const ADD_SHOWTIME = "ADD_SHOWTIME";
export const DELETE_SHOWTIME = "DELETE_SHOWTIME";

// Roles

export const FETCH_ALL_ROLES = "FETCH_ALL_ROLES";

// action type for movieReducer
export const FETCH_DATA_MOVIE = "FETCH_DATA_MOVIE";
export const FETCH_DATA_THEATER = "FETCH_DATA_THEATER";
export const FETCH_DATA_PROMOTION = "FETCH_DATA_PROMOTION";
export const FETCH_DATA_REVIEW_MOVIE = "FETCH_DATA_REVIEW_MOVIE";
export const FETCH_DATA_BOOKING_MOVIE = "FETCH_DATA_BOOKING_MOVIE";
export const FETCH_MOVIE = "FETCH_MOVIE";

export const RECEIVE_MOVIE_CHOOSING = "RECEIVE_MOVIE_CHOOSING";
export const SHOW_INFORMATION_MOVIE = "SHOW_INFORMATION_MOVIE";
export const RATING_ITEM_MOVIE = "RATING_ITEM_MOVIE";
export const RATING_ITEM_REVIEW_MOVIE = "RATING_ITEM_REVIEW_MOVIE";
export const CREATE_BOOKING = "CREATE_BOOKING";
export const GET_BOOKING = "GET_BOOKING";

// export const ADD_MOVIE = "ADD_MOVIE";
// export const DELETE_MOVIE = "DELETE_MOVIE";
// export const UPDATE_MOVIE = "UPDATE_MOVIE";
export const SEARCH_MOVIE = "SEARCH_MOVIE";

export const FETCH_SHOWTIMES = "FETCH_SHOWTIMES";
export const FETCH_DATA_USERS = "FETCH_DATA_USERS";
export const FETCH_DATA_SUPPORT = "FETCH_DATA_SUPPORT";
// export const FETCH_DATA_TICKETS_REQUEST = "FETCH_DATA_TICKETS_REQUEST";
export const FETCH_DATA_TICKETS = "FETCH_DATA_TICKETS";
export const FETCH_DATA_FOOD = "FETCH_DATA_FOOD";
export const FETCH_TRANSACTION = "FETCH_TRANSACTION";


//transactions

export const FETCH_DATA_TRANSACTION = "FETCH_DATA_TRANSACTION";
